version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: area_postgres
    environment:
      POSTGRES_USER: area_user
      POSTGRES_PASSWORD: area_password
      POSTGRES_DB: area_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U area_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - area_network

  # Redis for queues and cache
  redis:
    image: redis:7-alpine
    container_name: area_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - area_network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: area_server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://area_user:area_password@postgres:5432/area_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_change_in_production
      FRONTEND_URL: http://localhost:8081
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - area_network
    command: npm run dev

  # Mobile Client Builder
  client_mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: area_mobile_builder
    volumes:
      - mobile_apk:/app/android/app/build/outputs/apk
    networks:
      - area_network
    command: /bin/sh -c "npm install && cd android && ./gradlew assembleRelease && cp app/build/outputs/apk/release/app-release.apk /app/android/app/build/outputs/apk/client.apk"

  # Web Client
  client_web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: area_web_client
    ports:
      - "8081:8081"
    environment:
      VITE_API_URL: http://localhost:8080
    volumes:
      - ./web:/app
      - /app/node_modules
      - mobile_apk:/usr/share/nginx/html/download
    depends_on:
      - server
      - client_mobile
    networks:
      - area_network
    command: npm run dev -- --host 0.0.0.0 --port 8081

volumes:
  postgres_data:
  redis_data:
  mobile_apk:

networks:
  area_network:
    driver: bridge